/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#f4dfcb',
        'primary-fixed': '#cfe8df',
        'inverse-surface': '#3a2e21',
        'secondary-fixed-dim': '#ffb598',
        'on-tertiary-fixed-variant': '#494740',
        'on-secondary-fixed': '#370e00',
        'secondary-container': '#fd9e77',
        'surface-variant': '#f4dfcb',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b3ccc4',
        'surface-tint': '#4c635c',
        'secondary-fixed': '#ffdbce',
        'on-tertiary-container': '#aeaaa2',
        secondary: '#934a29',
        'on-surface-variant': '#424846',
        'on-secondary-fixed-variant': '#763314',
        surface: '#fff8f4',
        'on-background': '#241a0e',
        'on-secondary': '#ffffff',
        'primary-container': '#2d433d',
        'on-secondary-container': '#763315',
        background: '#fff8f4',
        'on-tertiary-fixed': '#1d1c16',
        'on-primary-fixed': '#091f1a',
        'tertiary-container': '#413f39',
        'on-primary-fixed-variant': '#354b45',
        'surface-container-low': '#fff1e6',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#e7e2d9',
        tertiary: '#2a2923',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#cac6be',
        'primary-fixed-dim': '#b3ccc4',
        'surface-container-high': '#fae5d1',
        'surface-container': '#ffead7',
        'surface-dim': '#ebd7c3',
        'outline-variant': '#c2c8c4',
        'on-primary': '#ffffff',
        primary: '#172d27',
        'surface-bright': '#fff8f4',
        'surface-container-lowest': '#ffffff',
        outline: '#727876',
        'on-surface': '#241a0e',
        'on-primary-container': '#97afa7',
        error: '#ba1a1a',
        'inverse-on-surface': '#ffeedf',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'stack-lg': '48px',
        unit: '8px',
        'container-padding-desktop': '40px',
        'container-padding-mobile': '20px',
        'stack-sm': '12px',
        'stack-md': '24px',
      },
      fontFamily: {
        'headline-md': ['Literata', 'serif'],
        'display-lg': ['Literata', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'data-mono': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Literata', 'serif'],
      },
      fontSize: {
        'headline-md': [
          '18px',
          {
            lineHeight: '26px',
            fontWeight: '600',
          },
        ],
        'display-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-md': [
          '13px',
          {
            lineHeight: '20px',
            fontWeight: '400',
          },
        ],
        'body-lg': [
          '15px',
          {
            lineHeight: '22px',
            fontWeight: '400',
          },
        ],
        'data-mono': [
          '13px',
          {
            lineHeight: '20px',
            letterSpacing: '-0.01em',
            fontWeight: '500',
          },
        ],
        'label-sm': [
          '11px',
          {
            lineHeight: '16px',
            letterSpacing: '0.01em',
            fontWeight: '600',
          },
        ],
        'display-lg-mobile': [
          '26px',
          {
            lineHeight: '34px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
      },
    },
  },
  plugins: [],
};
